import json
from typing import List, Dict, Any
from openai import OpenAI
from app.core.config import settings
from app.core.logging import logger

# Mapping from ISO 639-1 codes to full language names used in Gemma prompt
LANGUAGE_NAMES: Dict[str, str] = {
    "en": "English",
    "hi": "Hindi",
    "fr": "French",
    "de": "German",
    "es": "Spanish",
    "it": "Italian",
    "pt": "Portuguese",
    "ru": "Russian",
    "ja": "Japanese",
    "ko": "Korean",
    "zh": "Chinese",
    "ar": "Arabic",
}


class GemmaService:
    def __init__(self):
        self.api_key = settings.OPENROUTER_API_KEY
        self.base_url = settings.OPENROUTER_BASE_URL
        self.model = settings.OPENROUTER_MODEL

        # Initialize the OpenAI client pointing to OpenRouter
        # If API key is not configured, we gracefully degrade by bypassing LLM correction.
        self.client = None
        if self.api_key:
            self.client = OpenAI(
                api_key=self.api_key,
                base_url=self.base_url
            )
        else:
            logger.warning(
                "OPENROUTER_API_KEY is not set. Gemma enhancement service will bypass refinement and return raw segments."
            )

    def enhance_transcript(self, segments: List[Dict[str, Any]], language: str) -> List[Dict[str, Any]]:
        """
        Sends transcribed segments to Gemma 3:12B via OpenRouter to refine text.
        Corrects grammar, punctuation, spelling, and casing while strictly retaining
        timestamps. The system prompt is language-aware — Gemma is explicitly
        instructed to enhance in the source language and never translate.

        Args:
            segments (List[Dict[str, Any]]): List of raw subtitle segments with
                'start', 'end', and 'text' keys.
            language (str): Detected/selected language code (e.g. 'hi', 'fr').

        Returns:
            List[Dict[str, Any]]: Enhanced segments. Falls back to raw on errors.
        """
        if not self.client:
            logger.info("OpenRouter client not initialized (missing API key). Returning raw segments.")
            return segments

        if not segments:
            return []

        # Resolve the full language name for the prompt
        lang_name = LANGUAGE_NAMES.get(language, language.upper())
        logger.info(f"Enhancing {len(segments)} segments with {self.model} via OpenRouter (language: {lang_name})...")

        system_prompt = (
            f"You are an expert multilingual subtitle editor. The transcript you are editing is written in **{lang_name}**.\n\n"
            "Your task is to improve Automatic Speech Recognition (ASR) transcripts generated by Faster-Whisper.\n"
            "The transcript is already timestamped and segmented. Your responsibility is to improve the text quality "
            "**without changing the meaning or structure**.\n\n"
            "## Your Responsibilities\n"
            "1. Correct spelling mistakes.\n"
            "2. Correct grammatical errors.\n"
            "3. Correct punctuation.\n"
            "4. Restore capitalization where applicable for the language.\n"
            "5. Correct named entities (people, places, organizations, movies, TV shows, books, etc.).\n"
            "6. Fix obvious ASR recognition mistakes.\n"
            "7. Remove hallucinated or nonsensical words only when you are highly confident.\n"
            "8. Preserve the speaker's original intent and tone.\n"
            "9. Keep the transcript natural and readable.\n\n"
            "## CRITICAL LANGUAGE RULE\n"
            f"* The transcript is in **{lang_name}**. You MUST enhance it in **{lang_name}** only.\n"
            f"* Do NOT translate any part of the transcript to another language.\n"
            f"* Do NOT add English words unless they were clearly spoken in English in the original.\n\n"
            "## Do NOT\n"
            "* Do not summarize.\n"
            "* Do not rewrite sentences unnecessarily.\n"
            "* Do not paraphrase.\n"
            "* Do not shorten the transcript.\n"
            "* Do not expand the transcript.\n"
            "* Do not translate the transcript.\n"
            "* Do not censor content.\n"
            "* Do not invent missing information.\n"
            "* Do not change timestamps.\n"
            "* Do not merge or split subtitle blocks.\n"
            "* Do not reorder subtitles.\n\n"
            "## Preserve\n"
            "You must preserve:\n"
            "* Subtitle numbering\n"
            "* Start timestamps\n"
            "* End timestamps\n"
            "* Subtitle order\n"
            "* Number of subtitle blocks\n"
            "Only modify the subtitle text when necessary.\n\n"
            "## Confidence Rule\n"
            "If you are not confident about a correction, keep the original text.\n"
            "Never guess.\n\n"
            "## Input/Output Format\n"
            "You will receive a JSON list of subtitle segments with 'start', 'end', and 'text'.\n"
            "Return the EXACT SAME JSON list structure with the improved 'text' fields. "
            "Do not output anything other than the JSON array."
        )

        user_content = json.dumps(segments, ensure_ascii=False)

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_content}
                ],
                temperature=0.1,  # Low temperature for deterministic corrections
                extra_headers={
                    "HTTP-Referer": "https://github.com/CaptionForge",
                    "X-Title": "CaptionForge AI Subtitle Generator",
                }
            )

            response_text = response.choices[0].message.content or ""
            logger.info("Received response from OpenRouter.")

            # Clean markdown code block fences if present
            cleaned_text = response_text.strip()
            if cleaned_text.startswith("```"):
                lines = cleaned_text.splitlines()
                if lines[0].startswith("```"):
                    lines = lines[1:]
                if lines and lines[-1].startswith("```"):
                    lines = lines[:-1]
                cleaned_text = "\n".join(lines).strip()

            enhanced_segments = json.loads(cleaned_text)

            # Safety check: Ensure length matches the input
            if len(enhanced_segments) != len(segments):
                logger.warning(
                    f"Enhanced segment count mismatch: got {len(enhanced_segments)}, expected {len(segments)}. "
                    "Falling back to original segments."
                )
                return segments

            # Verify and copy timestamps over to prevent model from shifting them
            for i, seg in enumerate(enhanced_segments):
                seg["start"] = segments[i]["start"]
                seg["end"] = segments[i]["end"]
                if "text" not in seg:
                    seg["text"] = segments[i]["text"]

            logger.info(f"Successfully enhanced transcript with Gemma in {lang_name}.")
            return enhanced_segments

        except Exception as e:
            logger.error(f"Gemma transcript enhancement failed: {e}. Falling back to original segments.", exc_info=True)
            return segments

    def translate_text_for_tts(self, text: str, target_language: str) -> str:
        """
        Translates text to the target language for TTS generation.
        If the text is already in the target language, returns it as is.
        """
        if not self.client:
            logger.warning("OPENROUTER_API_KEY is not set. Bypassing TTS translation.")
            return text
            
        if not text.strip():
            return text

        lang_name = LANGUAGE_NAMES.get(target_language, target_language.upper())
        logger.info(f"Checking/translating TTS text to {lang_name} using {self.model} via OpenRouter...")

        system_prompt = (
            f"You are an expert, highly accurate translator. "
            f"Your task is to provide text for a Text-to-Speech (TTS) engine that expects text in **{lang_name}**.\n\n"
            f"RULES:\n"
            f"1. Translate the user's text into {lang_name}.\n"
            f"2. If the text is ALREADY entirely in {lang_name}, return it exactly as is without any changes.\n"
            f"3. Do NOT add any conversational filler, explanations, or quotes around the output.\n"
            f"4. Output ONLY the final {lang_name} text."
        )

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": text}
                ],
                temperature=0.1,
                extra_headers={
                    "HTTP-Referer": "https://github.com/CaptionForge",
                    "X-Title": "CaptionForge AI Subtitle Generator",
                }
            )
            translated_text = response.choices[0].message.content or ""
            # Clean any possible markdown code block fences just in case
            cleaned_text = translated_text.strip()
            if cleaned_text.startswith("```"):
                lines = cleaned_text.splitlines()
                if lines[0].startswith("```"):
                    lines = lines[1:]
                if lines and lines[-1].startswith("```"):
                    lines = lines[:-1]
                cleaned_text = "\n".join(lines).strip()
            
            logger.info(f"Successfully processed TTS translation to {lang_name}.")
            return cleaned_text if cleaned_text else text
        except Exception as e:
            logger.error(f"TTS translation failed: {e}. Falling back to original text.", exc_info=True)
            return text
